name: repo-sync

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *' # runs once a day
    # - cron: '*/15 * * * *' # every 15 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      # source
      - uses: actions/create-github-app-token@v2
        id: source-app-token
        with:
          app-id: ${{ vars.SOURCE_APP_ID }}
          private-key: ${{ secrets.SOURCE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # target
      - uses: actions/create-github-app-token@v2
        id: target-app-token
        with:
          app-id: ${{ vars.TARGET_APP_ID }}
          private-key: ${{ secrets.TARGET_APP_PRIVATE_KEY }}
          owner: joshjohanning-emu

      - name: Bulk GitHub Repository Sync
        uses: joshjohanning/bulk-github-repo-sync-action@v1
        with:
          repo-list-file: repos.yml
          source-github-token: ${{ steps.source-app-token.outputs.token }}
          target-github-token: ${{ steps.target-app-token.outputs.token }}
          overwrite-repo-visibility: true # overwrite repo visibility with what is in yml file; defaults to false
